"""
ContainmentSpecialist — wraps the generate_firewall_rules MCP tool.
Single responsibility: generate (NEVER apply) containment rule text for analyst review.

Architectural Guardrail:
  This specialist ONLY produces text strings. It never calls iptables, nft,
  any kernel interface, or any network API. The output must be manually reviewed
  and applied by a DFIR analyst. This is enforced by code structure, not prompts.
"""

import logging
import time
from datetime import datetime, timezone

log = logging.getLogger("sift_aid.specialists.containment")


class ContainmentSpecialist:
    """Generate containment recommendations. NEVER applies them automatically."""

    @staticmethod
    async def run(ips: list[str], domains: list[str]) -> dict:
        """
        Produce iptables and nftables rule text for analyst review.
        Returns structured dict with disclaimer. Never executes any command.
        """
        t0 = time.monotonic()

        # Deduplicate and cap inputs
        unique_ips = list(dict.fromkeys(ips))[:100]
        unique_domains = list(dict.fromkeys(domains))[:50]

        iptables_rules = []
        nftables_rules = []
        hosts_entries = []

        for ip in unique_ips:
            iptables_rules.append(f"iptables -I OUTPUT -d {ip} -j DROP")
            iptables_rules.append(f"iptables -I INPUT  -s {ip} -j DROP")
            nftables_rules.append(f"nft add rule ip filter output ip daddr {ip} drop")
            nftables_rules.append(f"nft add rule ip filter input  ip saddr {ip} drop")

        for domain in unique_domains:
            hosts_entries.append(f"0.0.0.0    {domain}")
            hosts_entries.append(f"::         {domain}")

        # Generate save/restore scripts for persistence (text only)
        iptables_restore_script = "\n".join([
            "#!/bin/sh",
            "# ANALYST REVIEW REQUIRED before executing this script",
            "# Generated by SIFT-AID — NOT automatically applied",
            "",
        ] + iptables_rules + [
            "",
            "iptables-save > /etc/iptables/rules.v4",
        ])

        result = {
            "generated_at": datetime.now(timezone.utc).isoformat(),
            "disclaimer": (
                "ANALYST REVIEW REQUIRED. SIFT-AID NEVER automatically applies "
                "firewall rules. These are recommendations only. Verify each IOC "
                "before blocking to avoid false-positive disruption."
            ),
            "ioc_summary": {
                "ip_count": len(unique_ips),
                "domain_count": len(unique_domains),
                "ips_to_block": unique_ips,
                "domains_to_block": unique_domains,
            },
            "iptables_rules": iptables_rules,
            "nftables_rules": nftables_rules,
            "hosts_file_entries": hosts_entries,
            "iptables_restore_script": iptables_restore_script,
            "elapsed_seconds": round(time.monotonic() - t0, 4),
        }

        log.info(
            "[ContainmentSpecialist] Generated rules for %d IPs, %d domains (NOT applied)",
            len(unique_ips),
            len(unique_domains),
        )
        return result
